### ISSUE TITLE
zone file incomplete or already outdated?

### ISSUE THREAD

**Issue by jomo** [mandatoryprogrammer/NorthKoreaDNSLeak#11]
For example the domain `gnu.rep.kp.` doesn't have any A records listed in this project, but there currently are some. Were these recently added or are they just missing in the repo?

```
$ dig ANY gnu.rep.kp +trace

[snip]

gnu.rep.kp.         43200   IN      SOA     ns1.gnu.rep.kp. postmaster.gnu.rep.kp. 2012110810 28800 7200 1209600 3600
gnu.rep.kp.         43200   IN      NS      ns2.gnu.rep.kp.
gnu.rep.kp.         43200   IN      NS      ns1.gnu.rep.kp.
gnu.rep.kp.         43200   IN      A       175.45.176.83
gnu.rep.kp.         43200   IN      A       175.45.176.73
;; Received 175 bytes from 175.45.176.9#53(175.45.176.9) in 307 ms
```

**Comment by mandatoryprogrammer** [comment]
Hey @jomo this data is only for North Korea's top level domains (`.kp`, `.edu.kp`, etc) in order to enumerate all of their websites. I do have a dump of `ANY` queries for their sites but it's not included here because they're outside of the scope of the `TLDR` research. Possibly worth adding the `ANY` queries against all the sites though just for completeness.

**Comment by jomo** [comment]
I see. Yep it would be worth it IMO since there are just a couple dozen domains.

**Comment by mandatoryprogrammer** [comment]
Will do later today :)
