### ISSUE TITLE
UTC instead of PDT or whatever..?

### ISSUE THREAD

**Issue by SilverCory** [mandatoryprogrammer/NorthKoreaDNSLeak#7]
Us folks from the rest of the world aren't to familiar with other timezones however to make life easier you could use UTC (as everyone should know their relevancy to UTC), a quick google says PDT is UTC-7, not too sure though.

**Comment by totoCZ** [comment]
The only correct time is KST – Korea Standard Time.

**Comment by SilverCory** [comment]
Pretty sure my point still stands there also..?

**Comment by totoCZ** [comment]
The Dear Leader does not wish for UTC to be used. KST is superior.

**Comment by mandatoryprogrammer** [comment]
I am now incredibly conflicted between wanting to make it easy to understand for everyone, and trolling with `KST`. Thinking I'm going to go with having both formats..

**Comment by chuushi** [comment]
@TomHetmer Our leader deems PYT as superior to KST.

KST is used by South Korea, and PYT (Pyongyang Time), which is 30 minutes behind KST, is used by our strong nation.  We moved _back_ to that time at August 15, 2015.  ("back" since that's what Korean Empire (Joseon) used to use before the Japanese occupation.)

PYT: UTC+08:30
KST: UTC+09:00

**Comment by totoCZ** [comment]
That must be a mistake? Best Korea is never 30 minutes behind anything.

(nice find, i didn't bother to re-check it :-)

**Comment by mandatoryprogrammer** [comment]
@SimonOrJ you're amazing, out-trolling the trolls :)

For my own sanity I'm just going to leave the timestamp as is, I don't think the conversions would be especially hard for people to do.
